" Configure GUI
set guitablabel=%N.\ %t%(\ %M%)
set guioptions-=T " Removes top toolbar
set guioptions-=F " Remove footer
set guioptions-=m " Remove menu bar
set guioptions+=a " Add autoselect
set guioptions-=r " Removes right hand scroll bar
set guioptions-=L " Removes left hand scroll bar for vertical Splits

set titlestring=%t%(\ %M%)%(\ (%{expand(\"%:~:.:h\")})%)
set winminheight=0

" Disable MacVim mapping for CMD+E
macm Edit.Find.Use\ Selection\ for\ Find	key=<nop>

" Add the actual keyboard shortcuts
nnoremap <D-1> 1gt
nnoremap <D-2> 2gt
nnoremap <D-3> 3gt
nnoremap <D-4> 4gt
nnoremap <D-5> 5gt
nnoremap <D-6> 6gt
nnoremap <D-7> 7gt
nnoremap <D-8> 8gt
nnoremap <D-9> 9gt

" Load common settings
source $DOTFILES_PATH/vim/config/config.vim
